# app/constants/error_codes.py
"""
Centralized error codes for the application.
All error codes should be defined here and used throughout the application.
"""

# Authentication & Authorization Errors
EMAIL_ALREADY_REGISTERED = "EMAIL_ALREADY_REGISTERED"
INCORRECT_EMAIL_OR_PASSWORD = "INCORRECT_EMAIL_OR_PASSWORD"
UNAUTHORIZED = "UNAUTHORIZED"
FORBIDDEN = "FORBIDDEN"
TOKEN_EXPIRED = "TOKEN_EXPIRED"
TOKEN_INVALID = "TOKEN_INVALID"

# User Errors
USER_NOT_FOUND = "USER_NOT_FOUND"
USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS"
USER_INACTIVE = "USER_INACTIVE"

# Question Errors
QUESTIONS_NOT_FOUND = "QUESTIONS_NOT_FOUND"
QUESTION_NOT_FOUND = "QUESTION_NOT_FOUND"
CATEGORY_NOT_FOUND = "CATEGORY_NOT_FOUND"
TEST_NOT_FOUND = "TEST_NOT_FOUND"

# Submission Errors
SUBMISSION_NOT_FOUND = "SUBMISSION_NOT_FOUND"
SUBMISSION_INVALID = "SUBMISSION_INVALID"
SUBMISSION_ALREADY_EXISTS = "SUBMISSION_ALREADY_EXISTS"

# Validation Errors
VALIDATION_ERROR = "VALIDATION_ERROR"
INVALID_INPUT = "INVALID_INPUT"
MISSING_REQUIRED_FIELD = "MISSING_REQUIRED_FIELD"
INVALID_FORMAT = "INVALID_FORMAT"

# Server Errors
INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"
DATABASE_ERROR = "DATABASE_ERROR"

# HTTP Status Code based Error Codes (fallback)
HTTP_400 = "HTTP_400"
HTTP_401 = "HTTP_401"
HTTP_403 = "HTTP_403"
HTTP_404 = "HTTP_404"
HTTP_409 = "HTTP_409"
HTTP_422 = "HTTP_422"
HTTP_500 = "HTTP_500"
HTTP_503 = "HTTP_503"

